# Generated by Django 5.2.5 on 2026-07-11

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('activity', 'Activity'), ('show', 'Show'), ('beach_event', 'Beach Event')], max_length=20)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Weekly Schedule'), ('special', 'Special Dated Event')], default='weekly', max_length=20)),
                ('weekday', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('available_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='themepark_events/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='themepark.event')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeParkTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('channel', models.CharField(choices=[('online', 'Online'), ('entrance', 'At Entrance')], default='online', max_length=20)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='themepark.event')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themepark_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeParkPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_until', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='themepark.event')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeParkEntranceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channel', models.CharField(choices=[('online', 'Online'), ('entrance', 'At Entrance')], default='entrance', max_length=20)),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themepark_entrance_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialThemeParkEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Special Theme Park Event',
                'verbose_name_plural': 'Special Theme Park Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('themepark.event',),
        ),
        migrations.CreateModel(
            name='WeeklyThemeParkEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Weekly Theme Park Activity',
                'verbose_name_plural': 'Weekly Theme Park Activities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('themepark.event',),
        ),
    ]
