# Generated by Django 6.0.6 on 2026-06-18 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FerrySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('available_seats', models.PositiveIntegerField(default=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FerryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.hotelbooking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ferry.ferryschedule')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferry_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
