# Generated by Django 5.2.5 on 2026-07-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FerrySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, max_length=150)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('special', 'Special Date')], default='daily', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('date', models.DateField(blank=True, null=True)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('available_seats', models.PositiveIntegerField(default=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
